### ISSUE TITLE
Making deployment replicas key conditional with HPA

### ISSUE THREAD

**Issue by flamein** [lightstep/lightstep-microsatellite-helm-chart#25]
In https://github.com/lightstep/lightstep-microsatellite-helm-chart/blob/main/charts/lightstepsatellite/templates/deployment.yaml#L8 the template renders amount of replicas unconditionally

Would it be an option to either make it dependent on the value of `replicas` so we can exclude it from values.yml using `replicas: null` or omit this key if `autoscaling.enabled: true`?

Reasoning here is that on redeployment kubernetes will always start replicas amount of pods, before kicking in HPA and possibly scaling up. If `replicas` is omitted it will start with the previous amount of pods, providing for a smoother deployment

**Comment by gdvalle** [comment]
Hello! This all makes sense to me. We shouldn't have to set replicas if the HPA controls it, so I took your suggestion in https://github.com/lightstep/lightstep-microsatellite-helm-chart/pull/27 and did both: if the value is `null`, or autoscaling is on, omit it.  Please re-open as needed, and thanks for the report.
