### ISSUE TITLE
Possible legacy value defined in template

### ISSUE THREAD

**Issue by flamein** [lightstep/lightstep-microsatellite-helm-chart#26]
At these lines a possible legacy value has been defined in the template: https://github.com/lightstep/lightstep-microsatellite-helm-chart/blob/main/charts/lightstepsatellite/templates/deployment.yaml#L66-L67

Environment variable `COLLECTOR_REPORTER_BYTES_PER_PROJECT` is not described in documentation, and the value `.Values.lightstep.bytes_per_project` is not present in the `values.yaml` file shipped with the helm chart, causing the value to be rendered as empty in helm.

This is causing an issue for us since this renders to null when using kustomize on top of helm, and leaves a key without value in the final manifests

**Comment by gdvalle** [comment]
Hello! Thank you for the report.

This value is still a valid config parameter, but I think we can accommodate your setup here without a regression. I've submitted a fix in https://github.com/lightstep/lightstep-microsatellite-helm-chart/pull/28. Please try `2.0.16`, and re-open if you still have issues!
